apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fullstack-app
  name: fullstack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullstack-app
  strategy: {}
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
      - image: manojkrishnappa/devops-pipeline:c7e64ab5349ddfa09f5d88f1e8607b4dca12564b
        name: devops-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-service
spec:
  selector:
    app: fullstack-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  